Fix compile error: a user provided default ctor is required here
The clang 3.2 generated error is:

nt2/modules/test/benchmark/src/priority.cpp:70:33: error:
          default initialization of an object of const type 'const
          nt2::details::priority_booster' requires a user-provided
          default constructor
  static priority_booster const priority_booster;
                                ˆ